### PR TITLE
+ Config.ProviderConfig

### PR DESCRIPTION
**Pull request by liut**
Example:

```go

import "github.com/fasthttp/session/redis"

  // optional config
  config := session.Config{
    Key:    "dinosaurus",       // default: "sessionid"
    Lookup: "header",           // default: "cookie"
    Domain: "google.com",       // default: ""
    Expires: 30 * time.Minutes, // default: 2 * time.Hour
    Secure:  true,              // default: false
    ProviderConfig: &redis.Config{
			Host:        "127.0.0.1",
			Port:        6379,
			PoolSize:    8,
			IdleTimeout: 300,
			KeyPrefix:   "session",
		}
  }

  // create session handler
  sessions := session.New(config)

```

### CODE REVIEW

**Comment by Fenny** [comment]
@liut thanks for your PR! And sorry for the late reply, we just enabled auto-assign on this repo.

Regarding your PR, it looks great but we are currently working on a new Session middleware without wrapping around fasthttp/session. This should be released soon, until then we could merge this PR so it can be used until the next release. @thomasvvugt, what do you think?

**Comment by thomasvvugt** [comment]
Hi @liut and @Fenny ,
I have tested the above pull request and unfortunately importing dependancies doesn't work as simple as expected.
Since we aren't importing each provider into the session middleware, we get a nil pointer. The session store cannot find the Storer (see; https://cdn.discordapp.com/attachments/704683224147689533/705078014001807480/unknown.png)
Thanks for creating this pull request, @Fenny and I are working on a new Session middleware which is going to add this feature!

**Comment by Fenny** [comment]
Expect a release tomorrow :thumbs:

**Comment by liut** [comment]
@Fenny sorry for late reply.  the tag v1.0.0 is a better solution. thanks for your work.

**Pull request closed without merging**
